import './context.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {parseJobs2webList,collectJobs2web} from '../../../../../shared/job-search-core/scripts/lib/provider-jobs2web.mjs';
import {publicListCandidateProblem} from '../../../../../shared/job-search-core/scripts/lib/public-list-source-policy.mjs';
import {atsConfiguration} from '../../../../../shared/job-search-core/scripts/discover-waiqi-zero-websites.mjs';
import {workdayListPlaceholder} from '../../../../../shared/job-search-core/scripts/lib/providers-international.mjs';
import {isIndividualJobRoute} from '../../../../../shared/job-search-core/scripts/lib/career-link-scope.mjs';
const origin='https://test.jobs2web.com',source={company_id:'test',display_name:'Test',provider:'jobs2web_public',api_config:{origin}};
test('Company discovery blocks individual job paths and query IDs, retaining company/profile/list endpoints',()=>{
 for(const p of ['/jobs/123.html','/jobs/1','/job/Shanghai/123','/m/position/123','/job-detail-new/123/c/','/sfcareer/jobreqcareerpvt?jobId=1'])assert.equal(isIndividualJobRoute(origin+p),true,p);
 for(const p of ['/search/','/recruiting/company/123/','/django_rest/job-list/?company_id=123','/company?ka=job-detail-company_custompage','/api/v1/search/job/posts','/api/Jobad/GetJobAdPageList','/wecruit/positionInfo/listPosition/SU123'])assert.equal(isIndividualJobRoute(origin+p),false,p);
});
const page=(ids,total=ids.length,next=null,location='Shanghai, CN')=>`<span class="paginationLabel">Results <b>1–25</b> of <b>${total}</b></span>${ids.map(id=>`<tr class="data-row"><td><a href="/job/title/${id}/">Title ${id}</a><span class="jobLocation">${location}</span></td></tr>`).join('')}${next?`<a href="?optionsFacetsDD_country=CN&amp;startrow=${next}">Next</a>`:''}`;
const client=pages=>({records:[],async request({url}){const html=pages.shift();assert.notEqual(html,undefined);return {text:html,url,record:{http_status:200,response_file:'fixture'}};}});
test('Jobs2Web modern tiles expose stable IDs and locations without reading JD',()=>{const p=parseJobs2webList('<span id="tile-search-results-label">Showing 1 to 1 of 1 Jobs</span><li class="job-tile job-id-1"><a href="/job/role/1/">Engineer</a><div id="job-1-desktop-section-location-value">Shanghai, China</div></li>',origin);assert.equal(p.total,1);assert.deepEqual(p.rows[0].locations,['Shanghai, China']);});
test('Jobs2Web list paginates observed links and does not request JD details',async()=>{const r=await collectJobs2web(source,{mode:'list',client:client([page([1],2,25),page([2],2)])});assert.equal(r.coverage.status,'complete');assert.equal(r.jobs.length,2);assert.ok(r.jobs.every(j=>!j.body_complete&&j.formal_status==='unknown'));});
test('Jobs2Web full mode never claims full JD coverage from list evidence',async()=>{const r=await collectJobs2web(source,{client:client([page([1])])});assert.equal(r.coverage.status,'partial');assert.equal(r.coverage.list_complete,true);});
test('Jobs2Web follows observed tile load-more definition with CN scope and detects repeated fragments',async()=>{
 const tile=id=>`<li class="job-tile"><a href="/job/title/${id}/">Engineer</a><div id="job-${id}-desktop-section-location-value">Shanghai, China</div></li>`;
 const initial='<span id="tile-search-results-label">Showing 1 to 1 of 2 Jobs</span>'+tile(1)+`<script>j2w.SearchResults.init({apiEndpoint:"tile-search-results",searchQuery:"?optionsFacetsDD_country=CN",jobRecordsPerPage:parseInt("1")});</script>`;
 const c=client([initial,tile(2)]),request=c.request;c.request=async q=>{if(q.url.includes('startrow'))assert.equal(new URL(q.url).pathname,'/tile-search-results/');return request(q);};
 assert.equal((await collectJobs2web(source,{mode:'list',client:c})).coverage.status,'complete');
 assert.equal((await collectJobs2web(source,{mode:'list',client:client([initial,tile(1)])})).coverage.status,'partial');
});
test('Jobs2Web repeated IDs and total drift stay partial',async()=>{for(const second of [page([1],2),page([2],3)]){const r=await collectJobs2web(source,{mode:'list',client:client([page([1],2,25),second])});assert.equal(r.coverage.status,'partial');assert.equal(r.coverage.list_complete,false);}});
test('Jobs2Web unexpected foreign rows and login HTML cannot pass',async()=>{const r=await collectJobs2web(source,{mode:'list',client:client([page([1],1,null,'Hong Kong, HK')])});assert.equal(r.jobs.length,0);assert.equal(r.coverage.status,'partial');assert.throws(()=>parseJobs2webList('<html>Login</html>',origin));});
test('Workday recruiting URL keeps observed tenant/site and public route',()=>{const s=atsConfiguration('https://wd3.myworkdaysite.com/recruiting/riotinto/RioTinto_Careers/job/Shanghai/Example_R123');assert.equal(s.api.url,'https://wd3.myworkdaysite.com/wday/cxs/riotinto/RioTinto_Careers/jobs');const j=workdayListPlaceholder({title:'Test',externalPath:'/job/Shanghai/Example_R123'},{...s,api_config:s.api_config},{},'not requested');assert.equal(j.official_url,'https://wd3.myworkdaysite.com/recruiting/riotinto/RioTinto_Careers/job/Shanghai/Example_R123');});
test('List-only admission rejects invented JD, unconfirmed identity and incomplete list',()=>{const c={provider:'jobs2web_public',verification_status:'verified_public_list_only',admitted:true,api_config:{origin},identity_verification:{identity_verified:true,official_name:'Test',evidence_file:'local',basis:'reviewed'},source_verification:{complete_jd_samples:0,proof_directory:'local',identity_basis:'reviewed',observed_jobs:1,public_list_capability:{anonymous:true,list_complete:true,jobs_observed:1,request_evidence:[{url:origin+'/search/?optionsFacetsDD_country=CN',http_status:200,anonymous_session_from_scratch:true,response_file:'local',response_sha256:'a'.repeat(64)}]}}};assert.equal(publicListCandidateProblem(c),null);for(const change of [x=>x.source_verification.complete_jd_samples=1,x=>x.identity_verification.identity_verified=false,x=>x.source_verification.public_list_capability.list_complete=false,x=>x.source_verification.public_list_capability.request_evidence[0].response_sha256='missing']){const d=structuredClone(c);change(d);assert.ok(publicListCandidateProblem(d));}});
